import Head from 'next/head'
import HeaderAction from '../components/common/header'
import { MentionsLegales } from '../components/common/mentions-legales'
import MentionsLegalesContent from '../components/mentions-legales/mentions-legales-content'

export default function Parasols() {
    return (
        <div>
            <Head>
                <title>Kancoon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href= "/FAVICON-transparent.png" />
            </Head>
            <HeaderAction></HeaderAction>
            <main className='pt-[95px] bg-dark-grey'>
                <MentionsLegalesContent></MentionsLegalesContent>
            </main>
            <MentionsLegales></MentionsLegales>
        </div>
    )
}