import Head from 'next/head'
import HeaderAction from '../components/common/header'
import Produit from '../components/parasols/produits'
import Realisations from '../components/parasols/realisations'

export default function Parasols() {
    return (
        <div>
            <Head>
                <title>Kancoon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href= "/FAVICON-transparent.png" />
            </Head>
            <HeaderAction></HeaderAction>
            <main className='pt-[95px] bg-dark-grey'>
                <Produit></Produit>
                <Realisations></Realisations>
                
            </main>

        </div>
    )
}