import Head from 'next/head'
import Footer from '../components/common/footer'
import Footer2 from '../components/common/footer-2'
import HeaderAction from '../components/common/header'
import { MentionsLegales } from '../components/common/mentions-legales'
import Produit from '../components/pergolas/produits'
import RealisationsPergolas from '../components/pergolas/realisations'
import Realisations from '../components/pergolas/realisations'

export default function Pergolas() {
    return (
        <div>
            <Head>
                <title>Kancoon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href= "/FAVICON-transparent.png" />
            </Head>
            <HeaderAction></HeaderAction>
            <main className='pt-[95px] bg-dark-grey'>
                <Produit></Produit>
                <RealisationsPergolas/>
            </main>
            <Footer2></Footer2>
            <MentionsLegales></MentionsLegales>

        </div>
    )
}